title: 한동수
author: hands8142
email: hands8142@kakao.com
tagline: Developer
description: > # this means to ignore newlines until "show_exerpts:"
  한동수 개발일지
analytics_id: 'UA-129158424-4'
social_links:
  github: hands8142
  # twitter: hands8142
  # linkedIn: in/hands8142